old pages as stub for expertise added + few style bugs fixes
PhoboSys/phobosys-site pull request #57
Opened 2020-09-03 15:49 UTC by IlyaKirsanov

2020-09-03 16:39 UTC, sergiylegmelnik requested changes

2020-09-03 16:39 UTC, sergiylegmelnik commented on src/components/Expertise/BigDataAnalytics/index.js
> +    this.html = document.getElementsByTagName('html')[0]
Extract this logic to some utility Class

2020-09-03 16:39 UTC, sergiylegmelnik commented on src/components/Expertise/ResearchDevelopment/index.js
> +                Ciklum R&D experts will cut your risk dramatically by examining the technical feasibility,
Replace all words 'Ciklum' with 'Phobosys'

2020-09-03 17:14 UTC, IlyaKirsanov commented on src/components/Expertise/BigDataAnalytics/index.js
> +    this.html = document.getElementsByTagName('html')[0]
done

2020-09-03 17:14 UTC, IlyaKirsanov commented on src/components/Expertise/ResearchDevelopment/index.js
> +                Ciklum R&D experts will cut your risk dramatically by examining the technical feasibility,
done

2020-09-04 10:28 UTC, sergiylegmelnik approved these changes

2020-09-04 10:28 UTC, merged