Assets
PhoboSys/phobosys-site pull request #77
Opened 2020-10-15 17:22 UTC by IlyaKirsanov

2020-10-19 17:49 UTC, sergiylegmelnik requested changes

2020-10-19 17:49 UTC, sergiylegmelnik commented on src/components/Modal/GetInTouch/index.js
> +            <img src="https://phobosys-assets.s3.us-east-2.amazonaws.com/img/close-btn-x.png" alt="close btn" />
You should use CloudFront link instead.

2020-10-19 17:50 UTC, sergiylegmelnik requested changes

2020-10-19 17:50 UTC, sergiylegmelnik commented on src/images&video/index.js
> +  allegion:'https://phobosys-assets.s3.us-east-2.amazonaws.com/svg/allegion.svg' ,
Move base link to the configuration file.

2020-10-19 18:14 UTC, IlyaKirsanov commented on src/images&video/index.js
> +  allegion:'https://phobosys-assets.s3.us-east-2.amazonaws.com/svg/allegion.svg' ,
please clerify, what exactly configuration file I should use for this base link

2020-10-19 18:14 UTC, IlyaKirsanov commented on src/components/Modal/GetInTouch/index.js
> +            <img src="https://phobosys-assets.s3.us-east-2.amazonaws.com/img/close-btn-x.png" alt="close btn" />
done

2020-10-21 12:14 UTC, sergiylegmelnik approved these changes

2020-10-21 12:14 UTC, merged